-- MySQL Script generated by MySQL Workbench
-- Mon Mar 11 23:51:08 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema consult
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema consult
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `consult` ;
-- -----------------------------------------------------
-- Schema pubsub
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pubsub
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pubsub` ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT NOT NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `full_name` VARCHAR(45) NULL,
  `date_of_birth` DATETIME NULL,
  `gender` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `location` GEOMETRY NULL,
  `email` VARCHAR(45) NULL,
  `avatar` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `deleted_at` DATETIME NULL,
  `last_login` DATETIME NULL,
  `ip` VARCHAR(45) NULL,
  `is_active` TINYINT NULL,
  `user_type` TINYINT NULL COMMENT 'Type of user: marketer or influencer',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`social_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`social_users` (
  `id` INT NOT NULL,
  `link` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `deleted_at` DATETIME NULL,
  `social_type` INT NULL COMMENT 'Enum (FACEBOOK, INSTAGRAM, TWITTER, YOUTUBE)',
  `access_token` VARCHAR(100) NULL,
  `account_id` INT NOT NULL,
  `extra_data` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_social_account_account_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `fk_social_account_account`
    FOREIGN KEY (`account_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`interest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`interest` (
  `id` INT NOT NULL,
  `tag_name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`account_interest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`account_interest` (
  `tags_id` INT NOT NULL,
  `social_account_id` INT NOT NULL,
  PRIMARY KEY (`tags_id`, `social_account_id`),
  INDEX `fk_tags_has_account_tags1_idx` (`tags_id` ASC) VISIBLE,
  INDEX `fk_account_tags_social_account1_idx` (`social_account_id` ASC) VISIBLE,
  CONSTRAINT `fk_tags_has_account_tags1`
    FOREIGN KEY (`tags_id`)
    REFERENCES `mydb`.`interest` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_account_tags_social_account1`
    FOREIGN KEY (`social_account_id`)
    REFERENCES `mydb`.`social_users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`conversations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`conversations` (
  `id` VARCHAR(100) NOT NULL,
  `last_message` VARCHAR(45) NULL,
  `last_time` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  `created_at` VARCHAR(45) NULL,
  `updated_at` VARCHAR(45) NULL,
  `msg_count` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users_conversations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users_conversations` (
  `id` INT NOT NULL,
  `joined_at` VARCHAR(45) NULL,
  `msg_count` INT NULL,
  `unread_message` INT NULL,
  `account_id` INT NOT NULL,
  `conversations_id` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_members_account1_idx` (`account_id` ASC) VISIBLE,
  INDEX `fk_members_conversations1_idx` (`conversations_id` ASC) VISIBLE,
  CONSTRAINT `fk_members_account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_members_conversations1`
    FOREIGN KEY (`conversations_id`)
    REFERENCES `mydb`.`conversations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`campaigns`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`campaigns` (
  `id` INT NOT NULL COMMENT '0000',
  `campaign_name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `content` VARCHAR(45) NULL,
  `posted_time` DATETIME NULL,
  `created_by` INT NULL,
  `status` VARCHAR(45) NULL COMMENT 'Start, running, finish',
  `start_time` DATETIME NULL,
  `end_time` DATETIME NULL,
  `platform_facebook` TINYINT NULL,
  `platform_instagram` TINYINT NULL,
  `platform_twitter` TINYINT NULL,
  `platform_youtube` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`hashtags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`hashtags` (
  `id` INT NOT NULL,
  `hashtag_name` VARCHAR(45) NULL,
  `description` VARCHAR(100) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`hashtags_campaigns`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`hashtags_campaigns` (
  `hashtag_id` INT NOT NULL,
  `campaigns_id` INT NOT NULL,
  `created_at` DATETIME NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`hashtag_id`, `campaigns_id`),
  INDEX `fk_hashtag_has_campaigns_campaigns1_idx` (`campaigns_id` ASC) VISIBLE,
  INDEX `fk_hashtag_has_campaigns_hashtag1_idx` (`hashtag_id` ASC) VISIBLE,
  CONSTRAINT `fk_hashtag_has_campaigns_hashtag1`
    FOREIGN KEY (`hashtag_id`)
    REFERENCES `mydb`.`hashtags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hashtag_has_campaigns_campaigns1`
    FOREIGN KEY (`campaigns_id`)
    REFERENCES `mydb`.`campaigns` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`campaign_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`campaign_users` (
  `campaign_id` INT NOT NULL,
  `influencer_id` INT NOT NULL,
  `status` INT NULL COMMENT 'invite, joined, apply, remove…',
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`campaign_id`, `influencer_id`),
  INDEX `fk_campaigns_has_account_account1_idx` (`influencer_id` ASC) VISIBLE,
  INDEX `fk_campaigns_has_account_campaigns1_idx` (`campaign_id` ASC) VISIBLE,
  CONSTRAINT `fk_campaigns_has_account_campaigns1`
    FOREIGN KEY (`campaign_id`)
    REFERENCES `mydb`.`campaigns` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_campaigns_has_account_account1`
    FOREIGN KEY (`influencer_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`interest_campaigns`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`interest_campaigns` (
  `tags_id` INT NOT NULL,
  `campaigns_id` INT NOT NULL,
  `created_at` DATETIME NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`tags_id`, `campaigns_id`),
  INDEX `fk_tags_has_campaigns_campaigns1_idx` (`campaigns_id` ASC) VISIBLE,
  INDEX `fk_tags_has_campaigns_tags1_idx` (`tags_id` ASC) VISIBLE,
  CONSTRAINT `fk_tags_has_campaigns_tags1`
    FOREIGN KEY (`tags_id`)
    REFERENCES `mydb`.`interest` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tags_has_campaigns_campaigns1`
    FOREIGN KEY (`campaigns_id`)
    REFERENCES `mydb`.`campaigns` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`messages` (
  `message_id` VARCHAR(45) NOT NULL,
  `body` VARCHAR(45) NULL,
  `is_image` TINYINT NULL,
  `is_file` TINYINT NULL,
  `sender_id` INT NULL,
  `receive_id` INT NULL,
  `time` INT NULL,
  `created_by` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `deleted_at` DATETIME NULL,
  `conversations_id` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`message_id`),
  INDEX `fk_messages_conversations1_idx` (`conversations_id` ASC) VISIBLE,
  CONSTRAINT `fk_messages_conversations1`
    FOREIGN KEY (`conversations_id`)
    REFERENCES `mydb`.`conversations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `consult` ;

-- -----------------------------------------------------
-- Table `consult`.`auth_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consult`.`auth_group` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `consult`.`django_content_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consult`.`django_content_type` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `app_label` VARCHAR(100) NOT NULL,
  `model` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `django_content_type_app_label_model_76bd3d3b_uniq` (`app_label` ASC, `model` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 23
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `consult`.`auth_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consult`.`auth_permission` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `content_type_id` INT(11) NOT NULL,
  `codename` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_permission_content_type_id_codename_01ab375a_uniq` (`content_type_id` ASC, `codename` ASC) VISIBLE,
  CONSTRAINT `auth_permission_content_type_id_2f476e4b_fk_django_co`
    FOREIGN KEY (`content_type_id`)
    REFERENCES `consult`.`django_content_type` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 67
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `consult`.`auth_group_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consult`.`auth_group_permissions` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `group_id` INT(11) NOT NULL,
  `permission_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_group_permissions_group_id_permission_id_0cd325b0_uniq` (`group_id` ASC, `permission_id` ASC) VISIBLE,
  INDEX `auth_group_permissio_permission_id_84c5c92e_fk_auth_perm` (`permission_id` ASC) VISIBLE,
  CONSTRAINT `auth_group_permissio_permission_id_84c5c92e_fk_auth_perm`
    FOREIGN KEY (`permission_id`)
    REFERENCES `consult`.`auth_permission` (`id`),
  CONSTRAINT `auth_group_permissions_group_id_b120cbf9_fk_auth_group_id`
    FOREIGN KEY (`group_id`)
    REFERENCES `consult`.`auth_group` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `consult`.`auth_user_groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consult`.`auth_user_groups` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `group_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_user_groups_user_id_group_id_94350c0c_uniq` (`user_id` ASC, `group_id` ASC) VISIBLE,
  INDEX `auth_user_groups_group_id_97559544_fk_auth_group_id` (`group_id` ASC) VISIBLE,
  CONSTRAINT `auth_user_groups_group_id_97559544_fk_auth_group_id`
    FOREIGN KEY (`group_id`)
    REFERENCES `consult`.`auth_group` (`id`),
  CONSTRAINT `auth_user_groups_user_id_6a12ed8b_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `consult`.`auth_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `consult`.`auth_user_user_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consult`.`auth_user_user_permissions` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `permission_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_user_user_permissions_user_id_permission_id_14a6b632_uniq` (`user_id` ASC, `permission_id` ASC) VISIBLE,
  INDEX `auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm` (`permission_id` ASC) VISIBLE,
  CONSTRAINT `auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm`
    FOREIGN KEY (`permission_id`)
    REFERENCES `consult`.`auth_permission` (`id`),
  CONSTRAINT `auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `consult`.`auth_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `consult`.`health_check_db_testmodel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consult`.`health_check_db_testmodel` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 639
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `consult`.`notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consult`.`notification` (
  `id` INT NOT NULL,
  `content` VARCHAR(100) NULL,
  `type` INT NULL,
  `created_at` DATETIME NULL,
  `seen` TINYINT NULL,
  `updated_at` DATETIME NULL,
  `deleted_at` DATETIME NULL,
  `reference_id` INT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`, `users_id`),
  INDEX `fk_notification_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_notification_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `consult`.`devices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consult`.`devices` (
  `id` INT NOT NULL,
  `device_token` VARCHAR(45) NULL,
  `platform` VARCHAR(45) NULL COMMENT 'IOS/ANDROID/WEB',
  `created_at` VARCHAR(45) NULL,
  `deleted_at` VARCHAR(45) NULL,
  `user_id` VARCHAR(45) NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`users_id`),
  CONSTRAINT `fk_devices_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `pubsub` ;

-- -----------------------------------------------------
-- Table `pubsub`.`auth_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pubsub`.`auth_group` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pubsub`.`django_content_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pubsub`.`django_content_type` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `app_label` VARCHAR(100) NOT NULL,
  `model` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `django_content_type_app_label_model_76bd3d3b_uniq` (`app_label` ASC, `model` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pubsub`.`auth_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pubsub`.`auth_permission` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `content_type_id` INT(11) NOT NULL,
  `codename` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_permission_content_type_id_codename_01ab375a_uniq` (`content_type_id` ASC, `codename` ASC) VISIBLE,
  CONSTRAINT `auth_permission_content_type_id_2f476e4b_fk_django_co`
    FOREIGN KEY (`content_type_id`)
    REFERENCES `pubsub`.`django_content_type` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 37
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pubsub`.`auth_group_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pubsub`.`auth_group_permissions` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `group_id` INT(11) NOT NULL,
  `permission_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_group_permissions_group_id_permission_id_0cd325b0_uniq` (`group_id` ASC, `permission_id` ASC) VISIBLE,
  INDEX `auth_group_permissio_permission_id_84c5c92e_fk_auth_perm` (`permission_id` ASC) VISIBLE,
  CONSTRAINT `auth_group_permissio_permission_id_84c5c92e_fk_auth_perm`
    FOREIGN KEY (`permission_id`)
    REFERENCES `pubsub`.`auth_permission` (`id`),
  CONSTRAINT `auth_group_permissions_group_id_b120cbf9_fk_auth_group_id`
    FOREIGN KEY (`group_id`)
    REFERENCES `pubsub`.`auth_group` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pubsub`.`auth_user_groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pubsub`.`auth_user_groups` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `group_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_user_groups_user_id_group_id_94350c0c_uniq` (`user_id` ASC, `group_id` ASC) VISIBLE,
  INDEX `auth_user_groups_group_id_97559544_fk_auth_group_id` (`group_id` ASC) VISIBLE,
  CONSTRAINT `auth_user_groups_group_id_97559544_fk_auth_group_id`
    FOREIGN KEY (`group_id`)
    REFERENCES `pubsub`.`auth_group` (`id`),
  CONSTRAINT `auth_user_groups_user_id_6a12ed8b_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `pubsub`.`auth_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pubsub`.`auth_user_user_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pubsub`.`auth_user_user_permissions` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `permission_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_user_user_permissions_user_id_permission_id_14a6b632_uniq` (`user_id` ASC, `permission_id` ASC) VISIBLE,
  INDEX `auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm` (`permission_id` ASC) VISIBLE,
  CONSTRAINT `auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm`
    FOREIGN KEY (`permission_id`)
    REFERENCES `pubsub`.`auth_permission` (`id`),
  CONSTRAINT `auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `pubsub`.`auth_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pubsub`.`health_check_db_testmodel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pubsub`.`health_check_db_testmodel` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `consult` ;

-- -----------------------------------------------------
-- Placeholder table for view `consult`.`consult_thread`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consult`.`consult_thread` (`latest_consult_id` INT, `latest_follow_up_id` INT, `latest_normal_consult_id` INT, `num_of_summary_patient` INT, `num_of_summary_doctor` INT, `thread_id` INT, `id` INT, `doctor_id` INT, `patient_id` INT, `created_by_id` INT);

-- -----------------------------------------------------
-- View `consult`.`consult_thread`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `consult`.`consult_thread`;
USE `consult`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`manadr`@`%` SQL SECURITY DEFINER VIEW `consult`.`consult_thread` AS select max(`C`.`id`) AS `latest_consult_id`,(select max(`consult`.`consult_module_consult`.`id`) from `consult`.`consult_module_consult` where ((`consult`.`consult_module_consult`.`is_follow_up` = 1) and (`consult`.`consult_module_consult`.`doctor_id` = `C`.`doctor_id`) and (`consult`.`consult_module_consult`.`patient_id` = `C`.`patient_id`) and (`consult`.`consult_module_consult`.`consult_for_id` = `C`.`consult_for_id`) and (`consult`.`consult_module_consult`.`type` = `C`.`type`))) AS `latest_follow_up_id`,(select max(`consult`.`consult_module_consult`.`id`) from `consult`.`consult_module_consult` where ((`consult`.`consult_module_consult`.`is_follow_up` = 0) and (`consult`.`consult_module_consult`.`doctor_id` = `C`.`doctor_id`) and (`consult`.`consult_module_consult`.`patient_id` = `C`.`patient_id`) and (`consult`.`consult_module_consult`.`consult_for_id` = `C`.`consult_for_id`) and (`consult`.`consult_module_consult`.`type` = `C`.`type`))) AS `latest_normal_consult_id`,count((case when (`C`.`health_summary_id` is not null) then 1 end)) AS `num_of_summary_patient`,count((case when (`C`.`status` = 3) then 1 end)) AS `num_of_summary_doctor`,concat(`C`.`doctor_id`,'_',`C`.`consult_for_id`,'_',`C`.`type`) AS `thread_id`,max(`C`.`id`) AS `id`,`C`.`doctor_id` AS `doctor_id`,`C`.`consult_for_id` AS `patient_id`,`C`.`patient_id` AS `created_by_id` from `consult`.`consult_module_consult` `C` group by `thread_id`;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
